sync:
  image: n3llyb0y/wait
  links:
    - auth
    - swagger-validator
    - postgres
  environment:
    PORTS: "9497 8080 5432"
auth:
   image: wazopbx/wazo-auth-tests
   links:
    - postgres
   expose:
     - "9497"
   volumes:
     - "../../..:/usr/src/wazo-auth"
     - "./etc/wazo-auth/config.yml:/etc/wazo-auth/config.yml"
     # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python2.7/site-packages/xivo"
   command: "wazo-auth"
swagger-validator:
  image: swaggerapi/swagger-validator
  ports:
    - "8080"
  links:
    - auth
postgres:
  image: wazopbx/wazo-auth-db
  expose:
    - "5432"
