debug: True
foreground: True
log_filename: /tmp/xivo-auth.log

rest_api:
  listen: 0.0.0.0
  port: 9497
  cors:
    enabled: True
    allow_headers: Content-Type, authorization

enabled_plugins:
  - mock
  - broken_init
  - broken_verify_password

ssl:
  cert_file: /data/ssl/server.crt
  key_file: /data/ssl/server.key

amqp:
  uri: amqp://guest:guest@localhost:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  host: consul
  port: 8500
  token: 'the_one_ring'
