debug: True
foreground: True
log_filename: /tmp/wazo-auth.log
token_cleanup_interval: 2.0

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: [Content-Type, authorization, x-auth-token]

enabled_http_plugins:
  users: true
enabled_plugins:
  - mock
  - mock_with_uuid
  - broken_init
  - broken_verify_password
  - wazo_user
backend_policies:
  wazo_user: wazo_default_admin_policy # For testing only, not a legitimate configuration

db_uri: postgresql://asterisk:proformatique@postgres:5432
