# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

log_filename: /tmp/wazo-auth.log
foreground: True
debug: True

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
  cors:
    enabled: False
    allow_headers: [Content-Type, authorization, x-auth-token]

enabled_backend_plugins:
  ldap_user: true

ldap:
  uri: ldap://slapd
  bind_anonymous: true
  user_base_dn: "dc=wazo-auth,dc=wazo,dc=community"
  user_login_attribute: 'mail'

db_uri: postgresql://asterisk:proformatique@postgres/asterisk
backend_policies:
  ldap_user: none
