# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/xivo-auth/conf.d/

log_filename: /var/log/xivo-auth.log
pid_filename: /var/run/xivo-auth/xivo-auth.pid
foreground: False
debug: False

# The lifetime of tokens in seconds
default_token_lifetime: 7200

# REST API server
rest_api:

  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /usr/share/xivo-certs/server.crt
    private_key: /usr/share/xivo-certs/server.key

    # SSL ciphers
    ciphers: "ALL:!aNULL:!eNULL:!LOW:!EXP:!RC4:!3DES:!SEED:+HIGH:+MEDIUM"

    #CORS configuration. See Flask-CORS documentation for other values.
  cors:
    enabled: True

    #Allow JSON preflight requests
    allow_headers: Content-Type, authorization, x-auth-token


enabled_plugins:
  - xivo_admin
  - xivo_service
  - xivo_user
  - xivo_ws

services:
  xivo-dird-phoned:
    key_file: /var/lib/xivo-auth-keys/xivo-dird-phoned-key.yml
    acls:
      -
        rule: 'xivo/private'
        policy: 'read'

  xivo-agid:
    key_file: /var/lib/xivo-auth-keys/xivo-agid-key.yml
    acls:
      -
        rule: 'xivo/private'
        policy: 'read'

amqp:
  uri: amqp://guest:guest@localhost:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  scheme: https
  host: localhost
  port: 8500
  verify: /usr/share/xivo-certs/server.crt
  token: 'the_one_ring'

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk
