general:
  listen: 0.0.0.0
  port: 6000
  debug: true
  cors:
    enabled: True
    allow_headers: Content-Type


plugins:
  - auth

amqp:
  uri: amqp://guest:guest@localhost:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  host: localhost
  port: 8500
  token: 'the_one_ring'

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk
