sync:
  image: n3llyb0y/wait
  links:
    - auth
    - consul
    - rabbitmq
  environment:
    PORTS: "9497 5672 8500"
auth:
   image: xivo/xivo-auth-tests
   ports:
     - "9497:9497"
   volumes:
     - "./etc/xivo-auth:/etc/xivo-auth"
     - "./logs:/tmp"
   links:
     - "rabbitmq"
     - "consul"
   command: "sh -c 'xivo-auth -u www-data 2>&1 | tee /tmp/xivo-auth.log'"
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
consul:
  image: progrium/consul
  expose:
    - "8500"
  volumes:
    - "./etc/consul:/config"
  command: "-client 0.0.0.0"
