debug: True
foreground: True
log_filename: /tmp/xivo-auth.log

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: Content-Type, authorization, x-auth-token

enabled_plugins:
  - mock
  - mock_with_uuid
  - broken_init
  - broken_verify_password
  - xivo_service

services:
  test-service:
    acls:
      -
        rule: 'xivo/private'
        policy: 'read'
    key_file: /data/service/service_keys/xivo-test-service-key.yml

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  scheme: https
  host: consul
  port: 8500
  token: 'the_one_ring'
  verify: /data/_common/ssl/consul/server.crt
