debug: True
foreground: True
log_filename: /tmp/xivo-auth.log
service_config_dir: "/data/service/etc/xivo-auth/services.d"

rest_api:
  listen: 0.0.0.0
  port: 9497
  cors:
    enabled: False
    allow_headers: Content-Type, authorization
  certificate: /data/_common/ssl/server.crt
  private_key: /data/_common/ssl/server.key

enabled_plugins:
  - mock
  - mock_with_uuid
  - broken_init
  - broken_verify_password
  - xivo_service

services:
  test-service:
    acls:
      -
        rule: 'xivo/private/{identifier}/contacts/personal'
        policy: 'read'

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  scheme: https
  host: consul
  port: 8500
  token: 'the_one_ring'
  verify: /data/_common/ssl/consul/server.crt
