debug: True
foreground: True
log_filename: /tmp/xivo-auth.log

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/no_server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: Content-Type, authorization

enabled_plugins:
  - mock

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  scheme: https
  host: consul
  port: 8500
  token: 'the_one_ring'
  verify: /data/_common/ssl/consul/server.crt
db_uri: postgresql://asterisk:proformatique@postgres:5432