# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

log_filename: /tmp/xivo-auth.log
foreground: True
debug: True

rest_api:
  https:
    host: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: Content-Type, authorization, x-auth-token
  ciphers: "ALL:!aNULL:!eNULL:!LOW:!EXP:!RC4:!3DES:!SEED:+HIGH:+MEDIUM"

enabled_plugins:
  - ldap_user_voicemail

services:
    xivo-dird-phoned:
        acls:
          -
            rule: 'xivo/private/{identifier}/contacts/personal'
            policy: 'read'

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  scheme: https
  host: consul
  port: 8500
  token: 'the_one_ring'
  verify: /data/_common/ssl/consul/server.crt

ldap:
  uri: ldap://slapd
  bind_dn_format: "uid={username},dc=xivo-auth,dc=xivo,dc=io"
  domain: xivo-auth.com

db_uri: postgresql://asterisk:proformatique@postgres/asterisk
