log_filename: /tmp/xivo-auth.log
foreground: True
debug: True
rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: [Content-Type, authorization, x-auth-token]
enabled_plugins:
  - ldap_user
ldap:
  uri: ldap://slapd
  user_base_dn: 'ou=quebec,ou=people,dc=xivo-auth,dc=wazo,dc=community'
  user_login_attribute: 'cn'
db_uri: postgresql://asterisk:proformatique@postgres:5432
backend_policies:
  ldap_user: none
