debug: True
foreground: True
log_filename: /tmp/xivo-auth.log
token_cleanup_interval: 2.0

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: [Content-Type, authorization, x-auth-token]

enabled_plugins:
  - mock
  - mock_with_uuid
  - broken_init
  - broken_verify_password

db_uri: postgresql://asterisk:proformatique@postgres:5432
