version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - postgres
      - rabbitmq
      - smtp
      - oauth2sync
    environment:
      TARGETS: "smtp:25 oauth2sync:80 auth:9497 postgres:5432 rabbitmq:5672"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  auth:
    image: wazopbx/wazo-auth-tests
    environment:
      TZ: UTC+1
      XIVO_UUID: the-predefined-xivo-uuid
    ports:
      - "9497"
    volumes:
      - "../../..:/usr/src/wazo-auth"
      - "./etc/wazo-auth/config.yml:/etc/wazo-auth/config.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python2.7/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python2.7/site-packages/xivo_bus"
    command: "wazo-auth"
  postgres:
    image: wazopbx/wazo-auth-db
    ports:
      - "5432"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
  smtp:
    image: munkyboy/fakesmtp
    ports:
      - "25"
  oauth2sync:
    image: oauth2-synchronization-service
    ports:
      - "80"
