version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - postgres
      - rabbitmq
      - smtp
      - oauth2sync
    environment:
      TARGETS: "smtp:25 oauth2sync:80 auth:9497 postgres:5432 rabbitmq:5672"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  auth:
    volumes:
      - "./etc/wazo-auth/conf.d/asset.external_auth.yml:/etc/wazo-auth/conf.d/asset.external_auth.yml"
