version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - postgres
      - rabbitmq
      - smtp
    environment:
      TARGETS: "auth:9497 postgres:5432 rabbitmq:5672 smtp:25"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  auth:
    volumes:
      - "./templates/raw_password_reset_email.base.jinja:/var/lib/wazo-auth/templates/raw_password_reset_email.jinja"
      - "./templates/email_confirmation_get_body.base.jinja:/var/lib/wazo-auth/templates/email_confirmation_get_body.jinja"
      - "./etc/wazo-auth/conf.d/asset.base.yml:/etc/wazo-auth/conf.d/asset.base.yml"

