version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - swagger-validator
      - postgres
      - rabbitmq
    environment:
      TARGETS: "auth:9497 swagger-validator:8080 postgres:5432 rabbitmq:5672"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
