version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - postgres
      - rabbitmq
      - smtp
    environment:
      TARGETS: "auth:9497 postgres:5432 rabbitmq:5672 smtp:25"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  auth:
    volumes:
      - "./base/var/lib/wazo-auth/templates/raw_password_reset_email.jinja:/var/lib/wazo-auth/templates/raw_password_reset_email.jinja"
      - "./base/var/lib/wazo-auth/templates/email_confirmation_get_body.jinja:/var/lib/wazo-auth/templates/email_confirmation_get_body.jinja"
      - "./base/etc/wazo-auth/config.yml:/etc/wazo-auth/config.yml"

