version: '3'
services:
  sync:
    depends_on:
      - auth
      - postgres
    environment:
      TARGETS: "auth:9497 postgres:5432"

  auth:
    volumes:
      - "./etc/wazo-auth/conf.d/asset.no_ssl_key.yml:/etc/wazo-auth/conf.d/asset.no_ssl_key.yml"
