# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

log_filename: /tmp/xivo-auth.log
foreground: True
debug: True

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/server.key
  cors:
    enabled: False
    allow_headers: Content-Type, authorization, x-auth-token

enabled_plugins:
  - ldap_user

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

ldap:
  uri: ldap://slapd
  bind_dn: 'cn=xivo_auth,ou=people,dc=xivo-auth,dc=xivo,dc=io'
  bind_password: 'S3cr$t'
  user_base_dn: 'dc=xivo-auth,dc=xivo,dc=io'
  user_login_attribute: 'uid'

db_uri: postgresql://asterisk:proformatique@postgres/asterisk
