debug: True
foreground: True
log_filename: /tmp/wazo-auth.log

rest_api:
  https:
    listen: 0.0.0.0
    port: 9497
    certificate: /data/_common/ssl/server.crt
    private_key: /data/_common/ssl/no_server.key
  cors:
    enabled: False
    allow_headers: [Content-Type, authorization, x-auth-token]

enabled_backend_plugins:
  mock: true

db_uri: postgresql://asterisk:proformatique@postgres:5432
